<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductsToSync($limit){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $q  = $qb->select(array('p'))
            ->where(
                $qb->expr()->gt('p.price', 0)
            )
            ->setMaxResults($limit)
            ->getQuery();

        return $q->getResult();
    }
}
